name: Deploy test application
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Build Project
        run: mvn clean install -DskipTests

      - name: Login DockerHub
        run: docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_PASSWORD}}

      - name: Build Docker image
        run: docker build -t edudanntas/pass-in .

      - name: Push Docker image
        run: docker push edudanntas/pass-in

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Pull image from DockerHub
        run: docker pull edudanntas/pass-in:latest

      - name: Run docker Container
        run: docker run -d -p 8080:8080 -e DATABASE_URL=${{secrets.DATABASE_URL}} -e DATABASE_USER=${{secrets.DATABASE_USER}} -e DATABASE_PSS='${{secrets.DATABASE_PSS}}' -e DATABASE_NAME=${{secrets.DATABASE_NAME}} --name pass-in edudanntas/pass-in